// Generated by tools/build-skill.ts from skills/orientim-protected-swap/src/verify.ts and @orientim/verifier. Do not edit.
import { SOLANA_ERROR__JSON_RPC__SERVER_ERROR_MIN_CONTEXT_SLOT_NOT_REACHED, TRANSACTION_CONFIG_COMPUTE_UNIT_LIMIT_BIT_MASK, TRANSACTION_CONFIG_LOADED_ACCOUNTS_DATA_SIZE_LIMIT_BIT_MASK, TRANSACTION_CONFIG_PRIORITY_FEE_LAMPORTS_BIT_MASK, address, decompileTransactionMessage, fetchAddressesForLookupTables, getAddressDecoder, getAddressEncoder, getCompiledTransactionMessageDecoder, getProgramDerivedAddress, getTransactionDecoder, getTransactionMessageComputeUnitLimit, getTransactionMessageLoadedAccountsDataSizeLimit, getTransactionMessagePriorityFeeLamports, getTransactionSize, isOffCurveAddress, isSignerRole, isSolanaError, isWritableRole } from "@solana/kit";
import "@solana/kit/program-client-core";
//#region node_modules/@solana-program/token/dist/src/index.mjs
async function findAssociatedTokenPda(seeds, config = {}) {
	const { programAddress = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" } = config;
	return await getProgramDerivedAddress({
		programAddress,
		seeds: [
			getAddressEncoder().encode(seeds.owner),
			getAddressEncoder().encode(seeds.tokenProgram),
			getAddressEncoder().encode(seeds.mint)
		]
	});
}
if (process.env["NODE_ENV"] !== "production");
if (process.env["NODE_ENV"] !== "production");
//#endregion
//#region packages/core/src/constants.ts
const SYSTEM_PROGRAM = address("11111111111111111111111111111111");
const TOKEN_PROGRAM = address("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA");
const TOKEN_2022_PROGRAM = address("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb");
const ATA_PROGRAM = address("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL");
const COMPUTE_BUDGET_PROGRAM = address("ComputeBudget111111111111111111111111111111");
const JUPITER_PROGRAM = address("JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4");
/** Native SOL is always handled as wrapped SOL (WSOL) inside the protected transaction. */
const WSOL_MINT = address("So11111111111111111111111111111111111111112");
const USDC_MINT = address("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v");
/**
* The tokens the Orientim fee is taken in first, on whichever side of the swap they are, the way
* Jupiter takes its own: SOL, then USDC, then USDT. Otherwise the fee is in the input token when the
* treasury has an account for it, and otherwise in SOL from the wallet at the swap's value (`sol`).
* A swap whose fee cannot be collected is refused (`fee-unavailable`); only a test deployment,
* without a treasury, is fee-free.
*/
const FEE_TOKENS = [
	WSOL_MINT,
	USDC_MINT,
	address("Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB")
];
const LEGACY_SIZE_LIMIT = 1232;
const V1_SIZE_LIMIT = 4096;
/**
* Base fee per signature. A cluster parameter, not a constant of nature: if it ever changes, R4
* would understate the fee. The pipeline also cross-checks with the RPC's getFeeForMessage.
*/
const LAMPORTS_PER_SIGNATURE = 5000n;
const BPS_DENOMINATOR = 10000n;
const MAX_FEE_BPS$1 = 100n;
const ABSOLUTE_MAX_NETWORK_FEE_LAMPORTS = 1000000n;
/**
* The most W may send E for rent of an account the route opens in E's name. Both of Pump.fun's
* markets open one per buyer (1,346,200 lamports in September 2026), and the bonding curve may add
* 132,080 for growing the curve's own account. A route that needs more is refused; a route that
* wants SOL to spend, not to rent with, cannot fit under it.
*/
const MAX_TAKER_RENT_LAMPORTS = 5000000n;
/**
* The most tolerance a person may choose (the page's slippage setting, or an agent's `slippageBps`):
* 15%. The page asks the verifier for the person's own choice, and the agent API and the skill's
* check for the number in the agent's own intent, never for more than this. Without a choice,
* routes keep the two ceilings above.
*/
const MAX_CHOSEN_SLIPPAGE_BPS = 1500;
/** Pump.fun's bonding-curve program: a route through it is priced on the curve. */
const PUMP_CURVE_PROGRAM = address("6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P");
/** PumpSwap, the market a Pump.fun token moves to after its curve. */
const PUMP_AMM_PROGRAM = address("pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA");
/**
* close_user_volume_accumulator, the same Anchor discriminator in both Pump programs' IDLs: closes
* the account a Pump market opens for every buyer and returns its lamports to the buyer, who in a
* Orientim swap is E. Accounts: [user (signer), account, event authority, program].
*/
const CLOSE_USER_VOLUME_ACCUMULATOR = [
	249,
	69,
	164,
	218,
	150,
	103,
	84,
	138
];
//#endregion
//#region packages/solana/src/index.ts
const MAX_ACCOUNTS_PER_CALL = 100;
const decodeBase64 = (s) => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));
/**
* A read that must not be older than `minContextSlot`: a node behind it says so, and is asked again
* a few times (it catches up in a slot or two) before the read fails.
*/
async function notOlderThan(read, minContextSlot) {
	for (let attempt = 0;; attempt++) try {
		return await read();
	} catch (e) {
		if (minContextSlot === void 0 || attempt >= 4 || !isSolanaError(e, SOLANA_ERROR__JSON_RPC__SERVER_ERROR_MIN_CONTEXT_SLOT_NOT_REACHED)) throw e;
		await new Promise((r) => setTimeout(r, 400));
	}
}
/**
* The same read, keeping the slot the chain answered at. With `minContextSlot`, every batch is at
* least that recent, so reads made in separate calls cannot mix state older than an earlier one.
*/
async function readAccounts(rpc, addresses, opts = {}) {
	const unique = [...new Set(addresses)];
	const out = /* @__PURE__ */ new Map();
	let slot = 0n;
	for (let i = 0; i < unique.length; i += MAX_ACCOUNTS_PER_CALL) {
		const batch = unique.slice(i, i + MAX_ACCOUNTS_PER_CALL);
		const { context, value } = await notOlderThan(() => rpc.getMultipleAccounts(batch, {
			encoding: "base64",
			commitment: "confirmed",
			...opts.minContextSlot !== void 0 ? { minContextSlot: opts.minContextSlot } : {}
		}).send(opts.timeoutMs ? { abortSignal: AbortSignal.timeout(opts.timeoutMs) } : void 0), opts.minContextSlot);
		const at = BigInt(context?.slot ?? 0);
		slot = slot === 0n || at !== 0n && at < slot ? at : slot;
		value.forEach((acc, j) => {
			out.set(batch[j], acc ? {
				owner: acc.owner,
				lamports: acc.lamports,
				data: decodeBase64(acc.data[0])
			} : null);
		});
	}
	return {
		accounts: out,
		slot
	};
}
/**
* A node finds a transaction's status in its status cache, which holds the transactions of its last
* 300 rooted blocks (Agave's MAX_RECENT_BLOCKHASHES), and only then in its ledger history or an
* archive. That history can be pruned or missing, and an archive that fails answers "no record" as
* well (Agave maps a BigTable error to none). So "no record" proves that a transaction never landed
* only while the node's cache still holds every block it could have landed in.
*/
const STATUS_CACHE_BLOCKS = 300n;
/**
* Does `view` prove that a transaction with no record in it never landed, and never will? It can
* land in blocks `earliest` to `lastValid`: the finalized chain must be past `lastValid`, and the
* answering node's cache must still reach down to `earliest`. Past that window, "no record" is no
* proof at all: the outcome stays unknown until someone looks it up in a full history.
*/
function provesNeverLanded(view, lastValid, earliest) {
	return view.coveredHeight !== null && view.reachHeight !== null && view.coveredHeight > lastValid && view.reachHeight + 30n < earliest + 300n;
}
/** Has the window in which "no record" could prove anything closed for good (see `provesNeverLanded`)? */
function pastProof(view, earliest) {
	return view.coveredHeight !== null && view.coveredHeight + 30n >= earliest + 300n;
}
//#endregion
//#region packages/verifier/src/parse.ts
const bytes = (d) => d ? Uint8Array.from(d) : /* @__PURE__ */ new Uint8Array();
const view = (b) => new DataView(b.buffer, b.byteOffset, b.byteLength);
const signerWritable = (a) => isSignerRole(a.role) && isWritableRole(a.role);
function parseInstruction(ix) {
	const program = ix.programAddress;
	const data = bytes(ix.data);
	const acc = ix.accounts ?? [];
	const invalid = (reason) => ({
		kind: "invalid",
		program,
		reason
	});
	if (program === COMPUTE_BUDGET_PROGRAM) {
		if (acc.length !== 0) return invalid("ComputeBudget instruction with accounts");
		if (data[0] === 2 && data.length === 5) return {
			kind: "cuLimit",
			units: view(data).getUint32(1, true)
		};
		if (data[0] === 3 && data.length === 9) return {
			kind: "cuPrice",
			microLamports: view(data).getBigUint64(1, true)
		};
		return invalid(`ComputeBudget instruction ${data[0]}`);
	}
	if (program === ATA_PROGRAM) {
		if (data.length !== 1 || data[0] !== 1) return invalid("ATA instruction other than CreateIdempotent");
		if (acc.length !== 6) return invalid("CreateIdempotent with unexpected accounts");
		const [payer, ata, owner, mint, system, tokenProgram] = acc;
		if (!signerWritable(payer) || !isWritableRole(ata.role)) return invalid("CreateIdempotent with wrong account roles");
		if (system.address !== SYSTEM_PROGRAM) return invalid("CreateIdempotent with wrong system program");
		if (tokenProgram.address !== TOKEN_PROGRAM && tokenProgram.address !== TOKEN_2022_PROGRAM) return invalid("CreateIdempotent with unknown token program");
		return {
			kind: "createAta",
			payer: payer.address,
			ata: ata.address,
			owner: owner.address,
			mint: mint.address,
			tokenProgram: tokenProgram.address
		};
	}
	if (program === TOKEN_PROGRAM || program === TOKEN_2022_PROGRAM) {
		const disc = data[0];
		if (disc === 12 && data.length === 10 && acc.length === 4) {
			const [source, mint, destination, authority] = acc;
			if (!isWritableRole(source.role) || !isWritableRole(destination.role) || !isSignerRole(authority.role)) return invalid("TransferChecked with wrong account roles");
			return {
				kind: "transferChecked",
				program,
				source: source.address,
				mint: mint.address,
				destination: destination.address,
				authority: authority.address,
				amount: view(data).getBigUint64(1, true),
				decimals: data[9]
			};
		}
		if (disc === 9 && data.length === 1 && acc.length === 3) {
			const [account, destination, owner] = acc;
			if (!isWritableRole(account.role) || !isWritableRole(destination.role) || !isSignerRole(owner.role)) return invalid("CloseAccount with wrong account roles");
			return {
				kind: "close",
				program,
				account: account.address,
				destination: destination.address,
				owner: owner.address
			};
		}
		if (disc === 26 && data.length === 2 && data[1] === 4 && program === TOKEN_2022_PROGRAM) {
			if (acc.length < 2) return invalid("Harvest without accounts");
			if (acc.some((a) => !isWritableRole(a.role))) return invalid("Harvest with a read-only account");
			return {
				kind: "harvest",
				program,
				mint: acc[0].address,
				sources: acc.slice(1).map((a) => a.address)
			};
		}
		if (disc === 5 && data.length === 1 && acc.length === 2) {
			const [source, owner] = acc;
			if (!isWritableRole(source.role) || !isSignerRole(owner.role)) return invalid("Revoke with wrong account roles");
			return {
				kind: "revoke",
				program,
				source: source.address,
				owner: owner.address
			};
		}
		if (disc === 17 && data.length === 1 && acc.length === 1 && program === TOKEN_PROGRAM) {
			if (!isWritableRole(acc[0].role)) return invalid("SyncNative on a read-only account");
			return {
				kind: "syncNative",
				account: acc[0].address
			};
		}
		return invalid(`Token instruction ${disc} (${data.length} bytes, ${acc.length} accounts)`);
	}
	if (program === SYSTEM_PROGRAM) {
		if (data.length === 12 && view(data).getUint32(0, true) === 2 && acc.length === 2) {
			const [from, to] = acc;
			if (!signerWritable(from) || !isWritableRole(to.role)) return invalid("System transfer with wrong account roles");
			return {
				kind: "systemTransfer",
				from: from.address,
				to: to.address,
				lamports: view(data).getBigUint64(4, true)
			};
		}
		return invalid(`System instruction ${data.length >= 4 ? view(data).getUint32(0, true) : "?"}`);
	}
	if (program === PUMP_CURVE_PROGRAM || program === PUMP_AMM_PROGRAM) {
		if (data.length !== 8 || CLOSE_USER_VOLUME_ACCUMULATOR.some((b, i) => data[i] !== b) || acc.length !== 4) return invalid("a Pump instruction other than closing the per-buyer account");
		const [user, account, eventAuthority, self] = acc;
		if (!signerWritable(user) || !isWritableRole(account.role) || isSignerRole(account.role) || isWritableRole(eventAuthority.role) || isSignerRole(eventAuthority.role) || self.address !== program || isWritableRole(self.role) || isSignerRole(self.role)) return invalid("close_user_volume_accumulator with wrong accounts or roles");
		return {
			kind: "closeRouteAccount",
			program,
			user: user.address,
			account: account.address,
			eventAuthority: eventAuthority.address
		};
	}
	return {
		kind: "external",
		program,
		accounts: acc,
		data
	};
}
//#endregion
//#region packages/verifier/src/verify.ts
const ata = async (owner, mint, tokenProgram = TOKEN_PROGRAM) => (await findAssociatedTokenPda({
	owner,
	mint,
	tokenProgram
}))[0];
const addressBytes = (a) => getAddressEncoder().encode(a);
const seed = (s) => new TextEncoder().encode(s);
/** The account a Pump market opens for E, and the program's event authority, derived here, not read. */
const routeAccountFor = async (program, E) => (await getProgramDerivedAddress({
	programAddress: program,
	seeds: [seed("user_volume_accumulator"), addressBytes(E)]
}))[0];
const eventAuthorityFor = async (program) => (await getProgramDerivedAddress({
	programAddress: program,
	seeds: [seed("__event_authority")]
}))[0];
function isTokenAccountOwnedBy(state, owner) {
	if (state.owner !== TOKEN_PROGRAM && state.owner !== TOKEN_2022_PROGRAM) return false;
	if (state.data.length < 165) return false;
	const want = addressBytes(owner);
	for (let i = 0; i < 32; i++) if (state.data[32 + i] !== want[i]) return false;
	return true;
}
const exists = (s) => !!s && (s.lamports > 0n || s.data.length > 0);
const u32At = (d, o) => new DataView(d.buffer, d.byteOffset, d.byteLength).getUint32(o, true);
const u64At = (d, o) => new DataView(d.buffer, d.byteOffset, d.byteLength).getBigUint64(o, true);
/** Token balance of a token account in the snapshot; 0 when it does not exist yet. */
const tokenBalance = (s) => s && s.data.length >= 72 ? u64At(s.data, 64) : 0n;
/** COption<close_authority> tag at offset 129 of an SPL token account. */
const hasCloseAuthority = (s) => !!s && s.data.length >= 165 && u32At(s.data, 129) === 1;
/**
* Token-2022 mint extensions a protected swap can live with. Everything else is refused, including
* any extension this list does not know: an extension changes what a transfer does, and what we
* have not read, we do not allow.
*
* Left out on purpose: pausable and non-transferable (a third party can stop the swap),
* interest-bearing and scaled UI amount (we would show a different number than the wallet),
* memo-required (every incoming transfer would need one more instruction). Three more are allowed
* only in a form that cannot act inside the transaction — transfer fee, permanent delegate and
* default account state; see `unsupportedExtension`.
*/
const ALLOWED_MINT_EXTENSIONS = /* @__PURE__ */ new Set([
	3,
	4,
	16,
	14,
	18,
	19,
	20,
	21,
	22,
	23
]);
/**
* The byte length each extension we interpret must declare. A length that disagrees with the
* program's own layout means we are not reading what we think we are reading, so the mint is
* refused rather than parsed further. Extensions of variable size - metadata and
* the group ones - are not listed here.
*/
const EXTENSION_LENGTH = {
	1: 108,
	3: 32,
	6: 1,
	12: 32,
	14: 64,
	16: 129,
	18: 64,
	20: 64,
	22: 64
};
const EXTENSION_NAMES = {
	1: "transfer fee",
	6: "accounts frozen by default",
	8: "memo required on transfer",
	9: "non-transferable",
	10: "interest-bearing",
	12: "permanent delegate",
	25: "scaled UI amount",
	26: "pausable",
	24: "confidential mint and burn",
	27: "pausable accounts",
	28: "permissioned burn"
};
/**
* Reads the TransferFeeConfig extension. Its value holds two authorities (32 bytes each), the
* withheld amount, and then the older and newer fee, each `{ epoch: u64, maximum: u64, bps: u16 }`.
* The newer one applies once its epoch has arrived, exactly as the token program decides it.
*/
function transferFeeOf(data, epoch) {
	if (data.length <= 165 || data[165] !== 1) return null;
	const view = new DataView(data.buffer, data.byteOffset, data.byteLength);
	for (let at = 166; at + 4 <= data.length;) {
		const type = view.getUint16(at, true);
		const length = view.getUint16(at + 2, true);
		const value = at + 4;
		if (type === 0) break;
		if (type === 1) {
			if (length < 108 || value + 108 > data.length) return null;
			const read = (from) => ({
				epoch: view.getBigUint64(from, true),
				maximum: view.getBigUint64(from + 8, true),
				bps: view.getUint16(from + 16, true)
			});
			const older = read(value + 72);
			const newer = read(value + 90);
			const active = epoch >= newer.epoch ? newer : older;
			return active.bps === 0 ? null : {
				bps: active.bps,
				maximum: active.maximum
			};
		}
		at = value + length;
	}
	return null;
}
/** What the token program withholds on a transfer of `amount`: rounded up, never above the cap. */
function transferFeeOn(amount, fee) {
	const raw = (amount * BigInt(fee.bps) + 9999n) / 10000n;
	return raw > fee.maximum ? fee.maximum : raw;
}
function hasTransferFee(data) {
	if (data.length <= 165 || data[165] !== 1) return false;
	const view = new DataView(data.buffer, data.byteOffset, data.byteLength);
	for (let at = 166; at + 4 <= data.length;) {
		const type = view.getUint16(at, true);
		const length = view.getUint16(at + 2, true);
		if (type === 0) break;
		if (type === 1) return true;
		at = at + 4 + length;
	}
	return false;
}
/**
* `allowTransferFee` is set for swap and intermediate mints whose temporary accounts are harvested
* before they are closed. Output accounts belong to the user and do not need to be closed.
*/
/** Does this mint have an issuer that can move or burn its balance anywhere (extension 12, set)? */
function hasPermanentDelegate(data) {
	if (data.length <= 165 || data[165] !== 1) return false;
	const view = new DataView(data.buffer, data.byteOffset, data.byteLength);
	for (let at = 166; at + 4 <= data.length;) {
		const type = view.getUint16(at, true);
		const length = view.getUint16(at + 2, true);
		const value = at + 4;
		if (type === 0) break;
		if (type === 12) return value + 32 <= data.length && data.subarray(value, value + 32).some((b) => b !== 0);
		at = value + length;
	}
	return false;
}
const addressDecoder = getAddressDecoder();
function unsupportedExtension(data, options = {}) {
	if (data.length === 82) return null;
	if (data.length <= 165 || data[165] !== 1) return "malformed extension area";
	const view = new DataView(data.buffer, data.byteOffset, data.byteLength);
	const nonZero = (from, to) => data.subarray(from, to).some((b) => b !== 0);
	for (let at = 166;;) {
		if (at === data.length) break;
		const padding = () => !nonZero(at, data.length);
		if (at + 4 > data.length) return padding() ? null : "malformed extension area";
		const type = view.getUint16(at, true);
		const length = view.getUint16(at + 2, true);
		const value = at + 4;
		if (type === 0) return padding() ? null : "malformed extension area";
		if (value + length > data.length) return "malformed extension";
		const expected = EXTENSION_LENGTH[type];
		if (expected !== void 0 && length !== expected) return `extension ${type} with a length of ${length}, not ${expected}`;
		if (type === 14) {
			if (length < 64 || nonZero(value + 32, value + 64)) return "transfer hook";
		} else if (type === 1) {
			if (!options.allowTransferFee) return "transfer fee";
		} else if (type === 12) {
			if (nonZero(value, value + 32) && isOffCurveAddress(addressDecoder.decode(data.subarray(value, value + 32)))) return "permanent delegate controlled by a program";
		} else if (type === 6) {
			if (data[value] !== 1) return "accounts frozen by default";
		} else if (!ALLOWED_MINT_EXTENSIONS.has(type)) return EXTENSION_NAMES[type] ?? `unknown extension ${type}`;
		at = value + length;
	}
	return null;
}
const ROUTE_V2 = [
	187,
	100,
	250,
	204,
	49,
	196,
	175,
	20
];
const SHARED_ACCOUNTS_ROUTE_V2 = [
	209,
	152,
	83,
	147,
	124,
	254,
	216,
	233
];
function jupiterRouteArgs(data) {
	const d = Uint8Array.from(data);
	const starts = (disc) => d.length >= 8 && disc.every((b, i) => d[i] === b);
	const base = starts(ROUTE_V2) ? 8 : starts(SHARED_ACCOUNTS_ROUTE_V2) ? 9 : -1;
	if (base < 0 || d.length < base + 22 + 4) return null;
	const v = new DataView(d.buffer, d.byteOffset, d.byteLength);
	return {
		inAmount: v.getBigUint64(base, true),
		quotedOutAmount: v.getBigUint64(base + 8, true),
		slippageBps: v.getUint16(base + 16, true),
		platformFeeBps: v.getUint16(base + 18, true),
		positiveSlippageBps: v.getUint16(base + 20, true),
		slippageOffset: base + 16
	};
}
/**
* The least a Jupiter route lets through: its quote less its tolerance, rounded down. Jupiter's
* program checks what its instruction delivered to the destination against this, so it holds
* whatever else arrives in that account.
*/
function jupiterFloor(args) {
	return args.quotedOutAmount * BigInt(1e4 - args.slippageBps) / 10000n;
}
/**
* The account Jupiter's route delivers to, which is the account its floor is measured on. From the program's IDL on chain:
*
*   route_v2:                 [0] authority, [1] source, [2] user destination, ..., [7] destination (optional)
*   shared_accounts_route_v2: [0] program authority, [1] authority, [2] source, ..., [5] destination
*
* An optional account left out is passed as the program's own address, and route_v2 then delivers to
* its user destination. Null for any other instruction, or too few accounts.
*/
function jupiterDestination(data, accounts) {
	const d = Uint8Array.from(data);
	const starts = (disc) => d.length >= 8 && disc.every((b, i) => d[i] === b);
	if (starts(ROUTE_V2) && accounts.length >= 10) return accounts[7] === JUPITER_PROGRAM ? accounts[2] : accounts[7];
	if (starts(SHARED_ACCOUNTS_ROUTE_V2) && accounts.length >= 12) return accounts[5];
	return null;
}
const V1_ALLOWED_CONFIG = TRANSACTION_CONFIG_PRIORITY_FEE_LAMPORTS_BIT_MASK | TRANSACTION_CONFIG_COMPUTE_UNIT_LIMIT_BIT_MASK | TRANSACTION_CONFIG_LOADED_ACCOUNTS_DATA_SIZE_LIMIT_BIT_MASK;
const BEFORE_SWAP = [
	"createEIn",
	"createEOut",
	"createWOut",
	"revokeWOut",
	"createIntermediate",
	"transferIn",
	"takerRent",
	"sync"
];
const AFTER_SWAP = [
	"minOutCheck",
	"harvestEIn",
	"harvestIntermediate",
	"closeEIn",
	"closeEOut",
	"closeIntermediate",
	"closeRouteAccount",
	"routeRefund"
];
/** Orientim's own cleanup of E's token accounts, all of which must be done before the route's account is closed. */
const OWN_CLEANUP = [
	"minOutCheck",
	"harvestEIn",
	"harvestIntermediate",
	"closeEIn",
	"closeEOut",
	"closeIntermediate"
];
async function verify(transaction, policy, snapshot, opts = {}) {
	const violations = [];
	const fail = (rule, detail) => void violations.push({
		rule,
		detail
	});
	const p = policy;
	const W = p.owner;
	const E = p.ephemeral;
	const variant = p.outputMint === WSOL_MINT ? "A" : p.inputMint === WSOL_MINT ? "B" : "C";
	if (p.variant !== variant) fail("R2", `policy variant ${p.variant} does not match the mints (${variant})`);
	const A = variant === "A";
	const B = variant === "B";
	const programOf = (mint) => {
		const state = snapshot.accounts.get(mint);
		if (!state) return null;
		return state.owner === TOKEN_PROGRAM || state.owner === TOKEN_2022_PROGRAM ? state.owner : null;
	};
	const chainInput = programOf(p.inputMint);
	const chainOutput = programOf(p.outputMint);
	if (chainInput && chainInput !== p.inputTokenProgram) fail("R2", "the input token program does not match the mint");
	if (chainOutput && chainOutput !== p.outputTokenProgram) fail("R2", "the output token program does not match the mint");
	const inputProgram = chainInput ?? p.inputTokenProgram;
	const outputProgram = chainOutput ?? p.outputTokenProgram;
	const inputMintState = snapshot.accounts.get(p.inputMint);
	const inputFee = !!inputMintState && inputProgram === TOKEN_2022_PROGRAM && hasTransferFee(inputMintState.data);
	if (inputMintState && p.inputTransferFee !== inputFee) fail("R2", `policy says the input mint ${p.inputTransferFee ? "charges" : "does not charge"} a transfer fee, the mint says otherwise`);
	if (p.feeSide !== null && p.feeSide !== "input" && p.feeSide !== "output" && p.feeSide !== "sol") fail("R2", "the policy names no fee side Orientim knows");
	if (p.treasury === null !== (p.feeSide === null)) fail("R2", "the policy has a treasury without a fee side, or the other way round");
	if (p.feeSide === "output" && !FEE_TOKENS.includes(p.outputMint)) fail("R2", "a fee on the output is taken only in SOL, USDC or USDT");
	if (p.feeSide === "sol" && (A || B)) fail("R2", "a fee in SOL from the wallet is only for a swap with no SOL on either side");
	if (p.feeSide === "sol" && p.fee < 0n) fail("R2", "policy amounts are inconsistent");
	const expectedFee = !p.treasury ? 0n : p.feeSide === "output" ? p.minOut * p.feeBps / BPS_DENOMINATOR : p.feeSide === "sol" ? p.fee : p.amountIn * p.feeBps / BPS_DENOMINATOR;
	const feeOnInput = p.feeSide === "input" ? p.fee : 0n;
	if (p.fee !== expectedFee || p.swapAmount + feeOnInput !== p.amountIn || p.swapAmount <= 0n) fail("R2", "policy amounts are inconsistent");
	if (p.inputMint === p.outputMint) fail("R2", "input and output token are the same");
	if (p.feeBps < 0n || p.feeBps > 100n) fail("R2", `fee of ${p.feeBps} bps is above the maximum of ${MAX_FEE_BPS$1}`);
	if (p.maxNetworkFeeLamports > 1000000n) fail("R4", `configured network fee limit ${p.maxNetworkFeeLamports} is above the absolute maximum`);
	if (p.minOut <= 0n) fail("R2", "the policy has no minimum output");
	for (const [mint, decimals, side] of [[
		p.inputMint,
		p.inputDecimals,
		"input"
	], [
		p.outputMint,
		p.outputDecimals,
		"output"
	]]) {
		const state = snapshot.accounts.get(mint);
		if (state && state.data.length >= 82 && state.data[44] !== decimals) fail("R2", `${side} decimals ${decimals} do not match the mint (${state.data[44]})`);
	}
	const refundProgram = p.routeRefundProgram;
	if (refundProgram !== null && refundProgram !== PUMP_CURVE_PROGRAM && refundProgram !== PUMP_AMM_PROGRAM) fail("R2", `route refund from ${refundProgram}, which is not a Pump market`);
	if (p.routeRefund > 0n !== (refundProgram !== null)) fail("R2", "policy route refund and its program disagree");
	if (p.routeRefund < 0n || p.routeRefund > 5000000n) fail("R4", `route refund ${p.routeRefund} lamports is outside 0..${MAX_TAKER_RENT_LAMPORTS}`);
	const refunds = refundProgram !== null && (refundProgram === PUMP_CURVE_PROGRAM || refundProgram === PUMP_AMM_PROGRAM);
	const expected = {
		routeAccount: refunds ? await routeAccountFor(refundProgram, E) : null,
		routeEventAuthority: refunds ? await eventAuthorityFor(refundProgram) : null,
		eIn: await ata(E, p.inputMint, inputProgram),
		eOut: A ? await ata(E, WSOL_MINT) : null,
		wIn: B ? null : await ata(W, p.inputMint, inputProgram),
		wOut: A ? null : await ata(W, p.outputMint, outputProgram),
		feeDestination: !p.treasury || !p.feeSide ? null : p.feeSide === "sol" ? p.treasury : p.feeSide === "input" ? B ? p.treasury : await ata(p.treasury, p.inputMint, inputProgram) : A ? p.treasury : await ata(p.treasury, p.outputMint, outputProgram)
	};
	const acc = p.accounts;
	if (acc.eIn !== expected.eIn || acc.eOut !== expected.eOut || acc.wIn !== expected.wIn || acc.wOut !== expected.wOut || acc.feeDestination !== expected.feeDestination || (acc.routeAccount ?? null) !== expected.routeAccount || (acc.routeEventAuthority ?? null) !== expected.routeEventAuthority) fail("R2", "policy accounts do not match their derivation");
	const { eIn, eOut, wIn, wOut, feeDestination } = expected;
	const minOut = A ? {
		account: eOut,
		authority: E,
		mint: WSOL_MINT,
		decimals: 9,
		amount: p.minOut,
		program: TOKEN_PROGRAM
	} : {
		account: wOut,
		authority: W,
		mint: p.outputMint,
		decimals: p.outputDecimals,
		program: outputProgram,
		amount: tokenBalance(snapshot.accounts.get(wOut)) + p.minOut
	};
	let compiled;
	let msg;
	try {
		compiled = getCompiledTransactionMessageDecoder().decode(transaction.messageBytes);
		msg = decompileTransactionMessage(compiled, { addressesByLookupTableAddress: snapshot.lookupTables });
	} catch (e) {
		fail("R1", `message accounts cannot be resolved: ${e.message}`);
		return {
			ok: false,
			violations
		};
	}
	if (msg.instructions.some((ix) => typeof ix.programAddress !== "string" || (ix.accounts ?? []).some((a) => typeof a?.address !== "string"))) {
		fail("R1", "an instruction names an account the message does not load");
		return {
			ok: false,
			violations
		};
	}
	const version = compiled.version;
	if (version !== 0 && version !== 1) fail("R5", `unsupported transaction version ${String(version)}`);
	const loaded = [...compiled.staticAccounts];
	const lookups = compiled.addressTableLookups ?? [];
	for (const l of lookups) {
		const table = snapshot.lookupTables[l.lookupTableAddress] ?? [];
		for (const i of [...l.writableIndexes, ...l.readonlyIndexes]) loaded.push(table[i]);
	}
	if (loaded.some((a) => typeof a !== "string")) {
		fail("R1", "a lookup names an account its table does not hold");
		return {
			ok: false,
			violations
		};
	}
	if (new Set(loaded).size !== loaded.length) fail("R5", "the message loads the same account more than once");
	const numSigners = compiled.header.numSignerAccounts;
	const signers = compiled.staticAccounts.slice(0, numSigners);
	if (compiled.staticAccounts[0] !== W) fail("R6", "the fee payer is not the wallet");
	if (!(signers.length === 2 && signers.includes(W) && signers.includes(E))) fail("R6", `unexpected signers: ${signers.join(", ")}`);
	const parsed = msg.instructions.map((ix) => parseInstruction(ix));
	parsed.forEach((x, i) => {
		if (x.kind === "invalid") fail("R2", `instruction ${i}: ${x.reason}`);
	});
	const externals = parsed.flatMap((x, i) => x.kind === "external" ? [{
		x,
		i
	}] : []);
	if (externals.length !== 1) fail("R2", `expected 1 external instruction, found ${externals.length}`);
	for (const { x } of externals) if (x.program !== p.jupiterProgram) fail("R2", `external program ${x.program} is not Jupiter`);
	const swapIndex = externals.length ? externals[0].i : -1;
	for (const { x } of externals) {
		if (x.kind !== "external" || x.program !== JUPITER_PROGRAM) continue;
		const args = jupiterRouteArgs(x.data);
		if (!args) {
			fail("R2", "the Jupiter instruction is not a route Orientim can read (route_v2 or shared_accounts_route_v2)");
			continue;
		}
		const curve = x.accounts.some((a) => a.address === PUMP_CURVE_PROGRAM);
		const chosen = opts.maxSlippageBps;
		const maxSlippage = chosen !== void 0 && Number.isInteger(chosen) && chosen >= 0 ? Math.min(chosen, MAX_CHOSEN_SLIPPAGE_BPS) : curve ? 300 : 50;
		if (args.platformFeeBps !== 0 || args.positiveSlippageBps !== 0) fail("R2", `the Jupiter route takes a platform fee (${args.platformFeeBps} bps) or positive slippage (${args.positiveSlippageBps} bps)`);
		if (args.slippageBps > maxSlippage) fail("R2", `the Jupiter route tolerates ${args.slippageBps} bps, above ${maxSlippage}`);
		const floor = jupiterFloor(args);
		if (floor < p.minOut) fail("R2", `the Jupiter route's own floor is ${floor} (${args.quotedOutAmount} less ${args.slippageBps} bps), below the minimum output ${p.minOut}`);
		if (args.inAmount <= 0n || args.inAmount > p.swapAmount) fail("R2", `the Jupiter route spends ${args.inAmount}, outside the approved ${p.swapAmount}`);
		const destination = jupiterDestination(x.data, x.accounts.map((a) => a.address));
		if (destination !== (A ? eOut : wOut)) fail("R2", `the Jupiter route delivers to ${destination ?? "an unreadable account"}, not to ${A ? "the temporary output account" : "the wallet's output account"}`);
	}
	const intermediates = /* @__PURE__ */ new Map();
	for (const x of parsed) {
		if (x.kind !== "createAta" || x.owner !== E || x.ata === eIn || x.ata === eOut) continue;
		if (x.mint === p.inputMint || A && x.mint === WSOL_MINT) continue;
		if (x.ata === await ata(E, x.mint, x.tokenProgram)) {
			const state = snapshot.accounts.get(x.mint);
			const fee = !!state && state.owner === TOKEN_2022_PROGRAM && hasTransferFee(state.data);
			intermediates.set(x.ata, {
				tokenProgram: x.tokenProgram,
				mint: x.mint,
				created: 0,
				closed: 0,
				fee
			});
		}
	}
	const slots = /* @__PURE__ */ new Map();
	const put = (s, i) => slots.set(s, [...slots.get(s) ?? [], i]);
	for (const [i, x] of parsed.entries()) switch (x.kind) {
		case "cuLimit":
			if (version === 1) fail("R4", "ComputeBudget instruction in a v1 transaction");
			else if (x.units > 14e5) fail("R4", `compute unit limit ${x.units} above maximum`);
			else put("cuLimit", i);
			break;
		case "cuPrice":
			if (version === 1) fail("R4", "ComputeBudget instruction in a v1 transaction");
			else put("cuPrice", i);
			break;
		case "createAta":
			if (x.payer !== W) {
				fail("R2", `instruction ${i}: account creation not paid by the wallet`);
				break;
			}
			if (x.tokenProgram === inputProgram && x.owner === E && x.mint === p.inputMint && x.ata === eIn) put("createEIn", i);
			else if (A && x.tokenProgram === TOKEN_PROGRAM && x.owner === E && x.mint === WSOL_MINT && x.ata === eOut) put("createEOut", i);
			else if (!A && x.tokenProgram === outputProgram && x.owner === W && x.mint === p.outputMint && x.ata === wOut) put("createWOut", i);
			else if (intermediates.has(x.ata)) {
				intermediates.get(x.ata).created++;
				put("createIntermediate", i);
			} else fail("R2", `instruction ${i}: unexpected account creation for ${x.owner}`);
			break;
		case "transferChecked": {
			const ours = x.program === inputProgram && x.source === wIn && x.mint === p.inputMint && x.authority === W && x.decimals === p.inputDecimals;
			const floor = x.program === minOut.program && x.source === minOut.account && x.destination === minOut.account && x.mint === minOut.mint && x.authority === minOut.authority && x.decimals === minOut.decimals;
			const outputFee = p.feeSide === "output" && !A && p.fee > 0n && x.program === outputProgram && x.source === wOut && x.mint === p.outputMint && x.authority === W && x.decimals === p.outputDecimals && x.destination === feeDestination && x.amount === p.fee;
			if (ours && x.destination === eIn && x.amount === p.swapAmount) put("transferIn", i);
			else if (ours && p.feeSide === "input" && p.fee > 0n && x.destination === feeDestination && x.amount === p.fee) put("feeTransfer", i);
			else if (outputFee) put("feeTransfer", i);
			else if (floor && x.amount === minOut.amount) put("minOutCheck", i);
			else if (floor) fail("R2", `instruction ${i}: minimum-output check for ${x.amount}, expected ${minOut.amount}`);
			else fail("R2", `instruction ${i}: unexpected token transfer of ${x.amount}`);
			break;
		}
		case "systemTransfer":
			if (B && x.from === W && x.to === eIn && x.lamports === p.swapAmount) put("transferIn", i);
			else if (B && p.feeSide === "input" && p.fee > 0n && x.from === W && x.to === feeDestination && x.lamports === p.fee) put("feeTransfer", i);
			else if (A && p.feeSide === "output" && p.fee > 0n && x.from === W && x.to === feeDestination && x.lamports === p.fee) put("feeTransfer", i);
			else if (p.feeSide === "sol" && p.fee > 0n && x.from === W && x.to === feeDestination && x.lamports === p.fee) put("feeTransfer", i);
			else if (p.takerRent > 0n && x.from === W && x.to === E && x.lamports === p.takerRent) put("takerRent", i);
			else if (p.routeRefund > 0n && x.from === E && x.to === W && x.lamports === p.routeRefund) put("routeRefund", i);
			else fail("R2", `instruction ${i}: unexpected SOL transfer of ${x.lamports} lamports`);
			break;
		case "syncNative":
			if (B && x.account === eIn) put("sync", i);
			else fail("R2", `instruction ${i}: unexpected SyncNative`);
			break;
		case "harvest": {
			const hop = x.sources.length === 1 ? intermediates.get(x.sources[0]) : void 0;
			if (x.program === inputProgram && x.mint === p.inputMint && x.sources.length === 1 && x.sources[0] === eIn) put("harvestEIn", i);
			else if (hop && hop.fee && x.program === hop.tokenProgram && x.mint === hop.mint) {
				hop.harvested = (hop.harvested ?? 0) + 1;
				put("harvestIntermediate", i);
			} else fail("R2", `instruction ${i}: unexpected harvest of withheld fees`);
			break;
		}
		case "revoke":
			if (!A && x.program === outputProgram && x.source === wOut && x.owner === W) put("revokeWOut", i);
			else fail("R2", `instruction ${i}: unexpected Revoke`);
			break;
		case "close": {
			if (x.destination !== W || x.owner !== E) {
				fail("R2", `instruction ${i}: account closed to someone other than the wallet`);
				break;
			}
			const mid = intermediates.get(x.account);
			if (x.program === inputProgram && x.account === eIn) put("closeEIn", i);
			else if (A && x.program === TOKEN_PROGRAM && x.account === eOut) put("closeEOut", i);
			else if (mid && mid.tokenProgram === x.program) {
				mid.closed++;
				put("closeIntermediate", i);
			} else fail("R2", `instruction ${i}: unexpected CloseAccount`);
			break;
		}
		case "closeRouteAccount": if (p.routeRefund > 0n && x.program === refundProgram && x.user === E && x.account === expected.routeAccount && x.eventAuthority === expected.routeEventAuthority) put("closeRouteAccount", i);
		else fail("R2", `instruction ${i}: a Pump account closed that the policy does not name`);
	}
	const count = (s) => slots.get(s)?.length ?? 0;
	const need = (s, n, rule = "R2") => {
		if (count(s) !== n) fail(rule, `expected ${n} × ${s}, found ${count(s)}`);
	};
	need("createEIn", 1);
	need("transferIn", 1);
	need("closeEIn", 1, "R5");
	if (A) {
		need("createEOut", 1);
		need("closeEOut", 1, "R5");
	} else {
		need("createWOut", 1);
		need("revokeWOut", 1);
	}
	need("minOutCheck", 1);
	need("harvestEIn", p.inputTransferFee ? 1 : 0, "R5");
	if (B) need("sync", 1);
	need("feeTransfer", p.fee > 0n ? 1 : 0);
	need("takerRent", p.takerRent > 0n ? 1 : 0, "R4");
	need("closeRouteAccount", p.routeRefund > 0n ? 1 : 0, "R5");
	need("routeRefund", p.routeRefund > 0n ? 1 : 0, "R5");
	if (p.takerRent < 0n || p.takerRent > 5000000n) fail("R4", `route rent ${p.takerRent} lamports is outside 0..${MAX_TAKER_RENT_LAMPORTS}`);
	if (version === 0) {
		need("cuLimit", 1, "R4");
		need("cuPrice", 1, "R4");
	}
	for (const [address, m] of intermediates) {
		if (m.created !== 1 || m.closed !== 1) fail("R5", `intermediate account ${address} is not created and closed exactly once`);
		if (m.fee && (m.harvested ?? 0) !== 1) fail("R5", `intermediate account ${address} of a taxing mint is not harvested exactly once`);
	}
	if (intermediates.size > 4) fail("R5", `${intermediates.size} intermediate accounts, above the maximum of 4`);
	if (swapIndex >= 0) {
		for (const s of BEFORE_SWAP) for (const i of slots.get(s) ?? []) if (i > swapIndex) fail("R2", `${s} must run before the swap`);
		for (const s of AFTER_SWAP) for (const i of slots.get(s) ?? []) if (i < swapIndex) fail("R5", `${s} must run after the swap`);
		for (const i of slots.get("feeTransfer") ?? []) {
			if (p.feeSide !== "output") {
				if (i > swapIndex) fail("R2", "feeTransfer must run before the swap");
				continue;
			}
			const first = [...slots.get("minOutCheck") ?? [], ...A ? slots.get("closeEOut") ?? [] : []];
			if (i < swapIndex || first.some((j) => j > i)) fail("R5", `the fee on the output must follow the minimum check${A ? " and the close of E_out" : ""}`);
		}
	}
	const first = (s) => slots.get(s)?.[0] ?? -1;
	if (first("createEIn") > first("transferIn")) fail("R2", "the input account is funded before it is created");
	if (B && first("transferIn") > first("sync")) fail("R2", "SyncNative runs before the SOL transfer");
	if (!A && first("createWOut") > first("revokeWOut")) fail("R2", "W_out is revoked before it is created");
	if (A && first("minOutCheck") > first("closeEOut")) fail("R5", "the minimum-output check runs after E_out is closed");
	if (p.inputTransferFee && first("harvestEIn") > first("closeEIn")) fail("R5", "withheld fees are harvested after E_in is closed");
	if (count("closeRouteAccount")) {
		const at = first("closeRouteAccount");
		if (at < Math.max(-1, ...OWN_CLEANUP.flatMap((s) => slots.get(s) ?? []))) fail("R5", "the route's account is closed while E still owns a token account");
		if (first("routeRefund") < at) fail("R5", "the route's lamports are sent on before its account is closed");
	}
	for (const { x } of externals) {
		if (x.kind !== "external") continue;
		for (const a of x.accounts) {
			if (a.address === W) {
				fail("R1", "the wallet is passed to the external program");
				continue;
			}
			if (a.address === wIn) {
				fail("R1", "the wallet's input token account is passed to the external program");
				continue;
			}
			if (a.address === feeDestination || a.address === p.treasury) {
				fail("R1", "Orientim's fee account is passed to the external program");
				continue;
			}
			if (a.address === wOut) continue;
			if (!snapshot.accounts.has(a.address)) {
				fail("R1", `external account ${a.address} missing from the snapshot`);
				continue;
			}
			const state = snapshot.accounts.get(a.address);
			if (state && isTokenAccountOwnedBy(state, W)) fail("R1", `the wallet's token account ${a.address} is passed to the external program`);
		}
	}
	if (wOut) {
		if (!snapshot.accounts.has(wOut)) fail("R1", "W_out missing from the snapshot");
		else if (hasCloseAuthority(snapshot.accounts.get(wOut))) fail("R1", "W_out has a close authority set");
	}
	const fromTables = new Set(loaded.slice(compiled.staticAccounts.length));
	const own = [
		["W_in", wIn],
		["W_out", wOut],
		["E_in", eIn],
		["E_out", eOut],
		["Orientim's fee account", feeDestination],
		["the treasury", p.treasury],
		["the route's account", expected.routeAccount],
		...[...intermediates.keys()].map((k) => ["an intermediate account", k])
	];
	for (const [label, address] of own) if (address && fromTables.has(address)) fail("R1", `${label} is loaded from a lookup table`);
	const fresh = [
		["E", E],
		["E_in", eIn],
		["E_out", eOut],
		...[...intermediates.keys()].map((k) => ["intermediate", k])
	];
	for (const [label, address] of fresh) {
		if (!address) continue;
		if (!snapshot.accounts.has(address)) fail("R3", `${label} missing from the snapshot`);
		else if (exists(snapshot.accounts.get(address))) fail("R3", `${label} already exists on chain`);
	}
	const signatureFee = LAMPORTS_PER_SIGNATURE * BigInt(numSigners);
	let priorityFee = 0n;
	if (version === 0) {
		const limit = parsed[first("cuLimit")];
		const price = parsed[first("cuPrice")];
		if (limit?.kind === "cuLimit" && price?.kind === "cuPrice") priorityFee = (BigInt(limit.units) * price.microLamports + 999999n) / 1000000n;
	} else if (version === 1) {
		const mask = compiled.configMask ?? 0;
		if (mask & ~V1_ALLOWED_CONFIG) fail("R4", `unexpected fields in the v1 message config (mask ${mask})`);
		const units = getTransactionMessageComputeUnitLimit(msg) ?? 0;
		if (units > 14e5) fail("R4", `compute unit limit ${units} above maximum`);
		const loaded = getTransactionMessageLoadedAccountsDataSizeLimit(msg) ?? 0;
		if (loaded > 67108864) fail("R4", `loaded accounts data size limit ${loaded} above maximum`);
		priorityFee = getTransactionMessagePriorityFeeLamports(msg) ?? 0n;
	}
	const feeLimit = p.maxNetworkFeeLamports < 1000000n ? p.maxNetworkFeeLamports : ABSOLUTE_MAX_NETWORK_FEE_LAMPORTS;
	if (signatureFee + priorityFee > feeLimit) fail("R4", `network fee up to ${signatureFee + priorityFee} lamports, above ${feeLimit}`);
	const size = getTransactionSize(transaction);
	const limit = version === 1 ? V1_SIZE_LIMIT : LEGACY_SIZE_LIMIT;
	if (size > limit) fail("R5", `transaction is ${size} bytes, limit ${limit}`);
	if (version === 1 && compiled.staticAccounts.length > 64) fail("R5", `${compiled.staticAccounts.length} accounts, limit 64`);
	for (const m of intermediates.values()) {
		if (m.tokenProgram !== TOKEN_2022_PROGRAM) continue;
		const state = snapshot.accounts.get(m.mint);
		const risky = state && state.owner === TOKEN_2022_PROGRAM ? unsupportedExtension(state.data, { allowTransferFee: true }) : "missing mint";
		if (risky) fail("R7", `intermediate mint ${m.mint}: ${risky}`);
	}
	for (const mint of [p.inputMint, p.outputMint]) {
		const state = snapshot.accounts.get(mint);
		if (!state) {
			fail("R7", `mint ${mint} not found`);
			continue;
		}
		if (state.owner === TOKEN_PROGRAM) continue;
		if (state.owner !== TOKEN_2022_PROGRAM) {
			fail("R7", `mint ${mint} is not a token mint`);
			continue;
		}
		const bad = unsupportedExtension(state.data, { allowTransferFee: true });
		if (bad) fail("R7", `mint ${mint}: ${bad}`);
	}
	return {
		ok: violations.length === 0,
		violations,
		networkFeeLamports: signatureFee + priorityFee
	};
}
//#endregion
//#region skills/orientim-protected-swap/src/verify.ts
/**
* The agent's own check of a prepared swap, before its wallet signs.
*
* Orientim's server built the transaction; the agent must not take its word for what it does. This
* runs Orientim's full verifier (`@orientim/verifier`, the same rules the page applies, R1–R7) on the exact
* bytes, against chain state the agent reads from ITS OWN RPC, and against a policy the agent holds
* to its own intent and limits. A compromised server, relay, DNS or impostor URL can then refuse or
* delay a swap, never make the agent sign one that moves anything but the approved amount.
*
* Two things the rules alone cannot settle are settled here too. The price: the
* agent must bring a floor of its own (`minOut`, from `ownMinimum` or its own source), or a server
* could sell the amount for almost nothing through a pool it controls. And the one-time key:
* the swap is simulated on the agent's RPC and must leave nothing under it, in its own account or
* in an account a Pump.fun market opens in its name, so no lamports stay where a server that
* derives the key could collect them. Rent a route keeps is a cost
* that does not come back, accepted only up to the agent's own limit (0.001 SOL by default).
*
* Bundled into ../lib/orientim-verify.mjs by tools/build-skill.ts (only @solana/kit stays external), so
* the skill works on its own; CI rebuilds it and fails if the committed file differs.
*/
/**
* Orientim's treasury wallet, pinned like the fee: unless the agent names another, Orientim's fee may go
* here or nowhere, whatever the server says.
*/
const ORIENTIM_TREASURY = "ARzSA3sZGhf5t4UnYrmB3TWyZ5m3Wo1nA9zWBcoiTqLE";
/** What the agent asked for, and the most it accepts. */
/**
* The tolerance an agent may choose for its route, as a person may on the page: 0.1% to 15%. Without
* a choice Orientim builds at 0.5%, or 3% on a Pump.fun bonding curve.
*/
const MIN_SLIPPAGE_BPS = 10;
const MAX_SLIPPAGE_BPS = 1500;
/** Above this price impact an agent refuses unless its owner allows more: the page asks a person there. */
const DEFAULT_MAX_PRICE_IMPACT_BPS = 500;
/**
* Hard limits no intent, flag or JSON field can raise. An agent sets its own
* limits, and an agent can be misled: a page, an issue or a token name that tells it to "set the
* minimum to 1" must not be able to sell the amount for nothing. Its floor never sits more than
* `MAX_BELOW_BPS` below Jupiter's own price, the price impact it accepts never exceeds
* `MAX_PRICE_IMPACT_BPS`, and Orientim's fee is never accepted above `MAX_FEE_BPS`. An owner who
* needs more changes these constants in their own copy, knowingly.
*/
const MAX_BELOW_BPS = 2e3;
const MAX_PRICE_IMPACT_BPS = 2e3;
const MAX_FEE_BPS = 30;
/** The fee limit the check applies: the agent's own, never above Orientim's pinned fee. */
const feeLimitBps = (maxFeeBps) => Number.isInteger(maxFeeBps) && maxFeeBps >= 0 ? Math.min(maxFeeBps, 30) : 30;
const isSlippageBps = (v) => typeof v === "number" && Number.isInteger(v) && v >= 10 && v <= 1500;
/**
* Orientim's fee in lamports when it is in SOL, whichever side it is taken from: from SOL the swap
* sells (`feeSide` input), from SOL it buys (output), or from the wallet for a pair that cannot carry
* it (sol). 0 when the fee is in another token.
*/
function solFeeOf(p) {
	return p.feeSide === "sol" || p.feeSide === "input" && p.inputMint === WSOL_MINT || p.feeSide === "output" && p.outputMint === WSOL_MINT ? p.fee : 0n;
}
const BIGINT_FIELDS = [
	"minOut",
	"takerRent",
	"routeRefund",
	"amountIn",
	"feeBps",
	"fee",
	"swapAmount",
	"maxNetworkFeeLamports"
];
const ADDRESS = /^[1-9A-HJ-NP-Za-km-z]{32,44}$/;
const isAddress = (v) => typeof v === "string" && ADDRESS.test(v);
/**
* Every other field of a policy the verifier reads, with the one shape it may take. A policy comes
* from the server, and the verifier repeats some of its fields in the problems it finds, which reach
* the agent: a field of any other shape (prose above all) makes the whole policy malformed.
*/
const POLICY_SHAPE = {
	owner: isAddress,
	ephemeral: isAddress,
	inputMint: isAddress,
	outputMint: isAddress,
	inputTokenProgram: isAddress,
	outputTokenProgram: isAddress,
	jupiterProgram: isAddress,
	inputTransferFee: (v) => typeof v === "boolean",
	inputDecimals: (v) => Number.isInteger(v) && v >= 0 && v <= 255,
	outputDecimals: (v) => Number.isInteger(v) && v >= 0 && v <= 255,
	routeRefundProgram: (v) => v === null || isAddress(v),
	treasury: (v) => v === null || isAddress(v),
	feeSide: (v) => v === null || v === "input" || v === "output" || v === "sol",
	variant: (v) => v === "A" || v === "B" || v === "C"
};
const ACCOUNT_FIELDS = [
	"eIn",
	"eOut",
	"wIn",
	"wOut",
	"feeDestination",
	"routeAccount",
	"routeEventAuthority"
];
function policyOf(json) {
	try {
		const accounts = json.accounts;
		if (!accounts || typeof accounts !== "object") return null;
		for (const k of ACCOUNT_FIELDS) if (!(accounts[k] === null || accounts[k] === void 0 || isAddress(accounts[k]))) return null;
		if (!isAddress(accounts.eIn)) return null;
		for (const [k, fits] of Object.entries(POLICY_SHAPE)) if (!fits(json[k])) return null;
		const p = { accounts: Object.fromEntries(ACCOUNT_FIELDS.map((k) => [k, accounts[k] ?? null])) };
		for (const k of Object.keys(POLICY_SHAPE)) p[k] = json[k];
		for (const k of BIGINT_FIELDS) {
			if (typeof json[k] !== "string" || !/^\d{1,20}$/.test(json[k])) return null;
			p[k] = BigInt(json[k]);
		}
		return p;
	} catch {
		return null;
	}
}
/** A value from the server, shown in a problem only as an address; anything else is not repeated. */
const shown = (v) => typeof v === "string" && /^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(v) ? v : "(not an address)";
const hex = (b) => Array.from(new Uint8Array(b), (x) => x.toString(16).padStart(2, "0")).join("");
/**
* The problems found, or an empty list. Sign only when it is empty. `rpc` must be the agent's own
* RPC, not one Orientim provides: the check is worth what the chain state it reads is worth.
*/
async function verifyPrepared(prepared, limits, rpc, opts = {}) {
	const timeoutMs = opts.requestTimeoutMs ?? 1e4;
	const problems = [];
	let transaction;
	try {
		transaction = getTransactionDecoder().decode(Buffer.from(prepared.transaction, "base64"));
	} catch {
		return ["the transaction cannot be decoded"];
	}
	if (hex(await crypto.subtle.digest("SHA-256", new Uint8Array(transaction.messageBytes))) !== prepared.messageSha256) problems.push("the message does not hash to messageSha256");
	const p = policyOf(prepared.policy);
	if (!p) return [...problems, "the policy is malformed"];
	if (p.owner !== limits.owner) problems.push(`the policy is for wallet ${shown(p.owner)}, not yours`);
	if (p.inputMint !== limits.inputMint || p.outputMint !== limits.outputMint) problems.push("the policy is for other tokens");
	if (p.amountIn !== BigInt(limits.amountIn)) problems.push(`the policy debits ${p.amountIn}, not ${limits.amountIn}`);
	if (p.jupiterProgram !== JUPITER_PROGRAM) problems.push(`the swap program is ${shown(p.jupiterProgram)}, not Jupiter`);
	if (p.ephemeral !== prepared.temporaryAuthority) problems.push("the one-time key differs from the one stated");
	if (p.feeBps > BigInt(feeLimitBps(limits.maxFeeBps))) problems.push(`the fee of ${p.feeBps} bps is above your limit`);
	if (p.treasury !== null && p.treasury !== (limits.treasury || "ARzSA3sZGhf5t4UnYrmB3TWyZ5m3Wo1nA9zWBcoiTqLE")) problems.push(`the fee goes to ${shown(p.treasury)}, not Orientim's treasury`);
	if (p.maxNetworkFeeLamports > BigInt(limits.maxNetworkFeeLamports ?? 1e6)) problems.push(`the network fee may reach ${p.maxNetworkFeeLamports} lamports, above your limit`);
	if (p.feeSide === "sol") {
		if (limits.maxSolFeeLamports === void 0) problems.push("the Orientim fee is paid in SOL at a price the check cannot see: set maxSolFeeLamports from a price you got yourself (ownSolFeeLimit asks Jupiter)");
		else if (p.fee > BigInt(limits.maxSolFeeLamports)) problems.push(`the Orientim fee in SOL is ${p.fee} lamports, above your limit of ${limits.maxSolFeeLamports}`);
	}
	const routeCost = p.takerRent - p.routeRefund;
	const maxRouteCost = BigInt(limits.maxRouteCostLamports ?? 1e6);
	if (routeCost > maxRouteCost) problems.push(`the route keeps ${routeCost} lamports of rent that do not come back, above your limit of ${maxRouteCost} (maxRouteCostLamports)`);
	const keeps = p.feeSide === "output" ? p.minOut - p.fee : p.minOut;
	if (!/^\d{1,20}$/.test(limits.minOut ?? "") || BigInt(limits.minOut) === 0n) problems.push("no minimum of your own: set minOut from a price you got yourself (ownMinimum asks Jupiter for one)");
	else if (keeps < BigInt(limits.minOut)) problems.push(`the minimum ${keeps} is below yours, ${limits.minOut}`);
	let snapshot;
	let snapshotAddresses = [];
	try {
		const compiled = getCompiledTransactionMessageDecoder().decode(transaction.messageBytes);
		const lookups = compiled.addressTableLookups ?? [];
		const lookupTables = lookups.length ? await fetchAddressesForLookupTables(lookups.map((l) => l.lookupTableAddress), rpc, { abortSignal: AbortSignal.timeout(timeoutMs) }) : {};
		const resolved = lookups.flatMap((l) => [...l.writableIndexes, ...l.readonlyIndexes].map((i) => lookupTables[l.lookupTableAddress]?.[i]).filter((a) => !!a));
		const derived = Object.values(p.accounts).filter((a) => !!a);
		const { accounts, slot } = await readAccounts(rpc, [
			...compiled.staticAccounts,
			...resolved,
			...derived,
			p.inputMint,
			p.outputMint,
			p.ephemeral,
			...p.treasury ? [p.treasury] : []
		], { timeoutMs });
		snapshot = {
			accounts,
			lookupTables,
			slot
		};
		snapshotAddresses = [...compiled.staticAccounts, ...resolved];
	} catch (e) {
		return [...problems, `the chain state could not be read from your RPC: ${e.message}`];
	}
	if (limits.slippageBps !== void 0 && !isSlippageBps(limits.slippageBps)) return [...problems, `slippageBps must be a whole number of bps from 10 to ${MAX_SLIPPAGE_BPS}`];
	const verdict = await verify(transaction, p, snapshot, limits.slippageBps !== void 0 ? { maxSlippageBps: limits.slippageBps } : {});
	for (const v of verdict.violations) problems.push(`${v.rule}: ${v.detail}`);
	if (limits.maxSolCostLamports !== void 0 && verdict.networkFeeLamports !== void 0) {
		const solCost = verdict.networkFeeLamports + routeCost + solFeeOf(p);
		if (solCost > BigInt(limits.maxSolCostLamports)) problems.push(`the swap may cost ${solCost} lamports of SOL that do not come back, above your limit of ${limits.maxSolCostLamports} (maxSolCostLamports)`);
	}
	const exists = (a) => {
		const s = snapshot.accounts.get(a);
		return !!s && (s.lamports > 0n || s.data.length > 0);
	};
	const keep = new Set([p.accounts.wOut, p.treasury].filter((a) => !!a));
	const fresh = [...new Set(snapshotAddresses)].filter((a) => !exists(a) && !keep.has(a));
	problems.push(...await leftUnderKey(prepared.transaction, p.ephemeral, rpc, snapshot.slot, timeoutMs, fresh));
	return problems;
}
/**
* What stays behind after the swap, simulated on the agent's own RPC: under the one-time key, in the
* account each Pump.fun market opens in its name, and in any other account the route opens. Every
* lamport the wallet sends E (a market's account rent) must be spent by the route or come back in the
* same transaction; a server that stated more than the route needs, a smaller refund, or a market
* account left open would otherwise leave lamports under a key it can derive. An account the route opens and leaves open may hold a claim tied to E
* whatever market it belongs to, so none may stay. An account that does not exist
* afterwards holds nothing; an answer that does not report the accounts proves nothing, and is refused.
*/
async function leftUnderKey(transaction, key, rpc, minContextSlot = 0n, timeoutMs = 1e4, fresh = []) {
	const markets = await Promise.all([PUMP_CURVE_PROGRAM, PUMP_AMM_PROGRAM].map((program) => routeAccountFor(program, key)));
	const cashback = await Promise.all(markets.flatMap((owner) => [WSOL_MINT, USDC_MINT].map(async (mint) => (await findAssociatedTokenPda({
		owner,
		mint,
		tokenProgram: TOKEN_PROGRAM
	}))[0])));
	const underKey = [
		key,
		...markets,
		...cashback
	];
	const opened = fresh.filter((a) => !underKey.includes(a));
	const watched = [...underKey, ...opened];
	try {
		const { value } = await rpc.simulateTransaction(transaction, {
			encoding: "base64",
			sigVerify: false,
			replaceRecentBlockhash: true,
			commitment: "confirmed",
			accounts: {
				addresses: watched,
				encoding: "base64"
			},
			...minContextSlot > 0n ? { minContextSlot } : {}
		}).send({ abortSignal: AbortSignal.timeout(timeoutMs) });
		if (value.err) return [`the swap fails in simulation on your RPC: ${JSON.stringify(value.err, (_, v) => typeof v === "bigint" ? v.toString() : v)}`];
		const after = value.accounts;
		if (!Array.isArray(after) || after.length !== watched.length) return ["the simulation on your RPC did not report what the one-time key holds after the swap"];
		const held = after.map((a) => BigInt(a?.lamports ?? 0));
		const problems = [];
		if (held[0] !== 0n) problems.push(`the one-time key would keep ${held[0]} lamports after the swap`);
		const inMarkets = held.slice(1, underKey.length).reduce((sum, x) => sum + x, 0n);
		if (inMarkets !== 0n) problems.push(`a market account under the one-time key would keep ${inMarkets} lamports after the swap`);
		const left = opened.filter((_, i) => held[underKey.length + i] !== 0n);
		if (left.length) problems.push(`the route would leave open ${left.length} account(s) it creates (${left.join(", ")}), holding lamports no one returns`);
		return problems;
	} catch (e) {
		return [`the swap could not be simulated on your RPC: ${e.message}`];
	}
}
/**
* A floor of the agent's own (`ownQuote`), for a swap within the price impact limit: an amount that
* moves the market more than `maxPriceImpactBps` (default 5%, at most 20%) is refused here, as the
* example and `orientim-verify` refuse it, so that a bot built on `ownMinimum` and `verifyPrepared`
* keeps that check. `verifyPrepared` itself checks the bytes against your limits, not the market.
*/
async function ownMinimum(args) {
	const limit = args.maxPriceImpactBps ?? 500;
	if (!(Number.isInteger(limit) && limit >= 0 && limit <= 2e3)) throw new Error(`maxPriceImpactBps must be a whole number of bps from 0 to ${MAX_PRICE_IMPACT_BPS}. Nothing was prepared.`);
	const own = await ownQuote(args);
	if (own.priceImpactBps !== null && own.priceImpactBps > limit) throw new Error(`Price impact is ${(own.priceImpactBps / 100).toFixed(2)}%, above the limit of ${(limit / 100).toFixed(2)}%: this amount would move the market too much. Nothing was prepared or signed.`);
	return own.minOut;
}
/**
* Jupiter's price for the amount Orientim will route, asked for directly: the agent's own floor
* (`minOut`, base units), how far this amount moves the market (`priceImpactBps`), and whether the
* route trades on a Pump.fun bonding curve. A large price impact is the mark of thin liquidity, as
* when a token's pool is drained: the check refuses it (`DEFAULT_MAX_PRICE_IMPACT_BPS`).
*/
async function ownQuote(args) {
	if (args.maxBelowBps !== void 0 && !(Number.isInteger(args.maxBelowBps) && args.maxBelowBps >= 0 && args.maxBelowBps <= 2e3)) throw new Error(`maxBelowBps must be a whole number of bps from 0 to ${MAX_BELOW_BPS}: a floor further below the market is not accepted. Nothing was prepared.`);
	const amount = BigInt(args.amountIn);
	const afterFee = amount - amount * BigInt(feeLimitBps(args.maxFeeBps)) / 10000n;
	const routed = args.inputTax ? afterFee - transferFeeOn(afterFee, args.inputTax) : afterFee;
	const url = new URL(args.jupiterUrl ?? "https://api.jup.ag/swap/v2/build");
	const query = {
		inputMint: args.inputMint,
		outputMint: args.outputMint,
		amount: routed.toString(),
		taker: args.taker,
		slippageBps: "50",
		maxAccounts: "64"
	};
	for (const [k, v] of Object.entries(query)) url.searchParams.set(k, v);
	const res = await (args.fetchImpl ?? fetch)(url.toString(), {
		headers: args.apiKey ? { "x-api-key": args.apiKey } : {},
		signal: AbortSignal.timeout(15e3)
	});
	if (!res.ok) throw new Error(`Jupiter answered ${res.status} when asked for your own price`);
	const r = await res.json();
	if (r.inputMint !== args.inputMint || r.outputMint !== args.outputMint || r.inAmount !== routed.toString() || !/^\d{1,20}$/.test(r.outAmount ?? "")) throw new Error("Jupiter answered for another trade when asked for your own price");
	const curve = r.swapInstruction?.accounts?.some((a) => a.pubkey === PUMP_CURVE_PROGRAM) ?? false;
	const below = BigInt(args.maxBelowBps ?? (args.slippageBps !== void 0 ? args.slippageBps + (curve ? 200 : 150) : curve ? 500 : 200));
	const impact = typeof r.priceImpactPct === "number" || typeof r.priceImpactPct === "string" && r.priceImpactPct.trim() !== "" ? Number(r.priceImpactPct) : NaN;
	if (!Number.isFinite(impact) && !args.allowUnknownImpact) throw new Error("Jupiter answered without a price impact when asked for your own price: how much this amount moves the market is unknown");
	return {
		minOut: (BigInt(r.outAmount) * (10000n - below) / 10000n).toString(),
		outAmount: r.outAmount,
		priceImpactBps: !Number.isFinite(impact) ? null : impact > 0 ? Math.round(impact * 1e4) : 0,
		curve
	};
}
/** Stablecoins and SOL keep authorities by design; a note on every swap of them would teach agents to skip notes. */
const QUIET_MINTS = /* @__PURE__ */ new Set([
	WSOL_MINT,
	USDC_MINT,
	"Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"
]);
async function tokenRisk(rpc, mints, timeoutMs = 1e4) {
	const asked = [...new Set(mints)];
	try {
		const { accounts } = await readAccounts(rpc, asked, { timeoutMs });
		const tokens = {};
		for (const m of asked) {
			const s = accounts.get(m);
			if (!s || s.data.length < 82 || s.owner !== TOKEN_PROGRAM && s.owner !== TOKEN_2022_PROGRAM) {
				tokens[m] = { exists: false };
				continue;
			}
			const view = new DataView(s.data.buffer, s.data.byteOffset, s.data.byteLength);
			tokens[m] = {
				freezeAuthority: view.getUint32(46, true) === 1,
				mintAuthority: view.getUint32(0, true) === 1,
				permanentDelegate: s.owner === TOKEN_2022_PROGRAM && hasPermanentDelegate(s.data),
				wellKnown: QUIET_MINTS.has(m)
			};
		}
		return {
			status: "known",
			tokens
		};
	} catch (e) {
		return {
			status: "unavailable",
			reason: e instanceof Error && e.name === "TimeoutError" ? "timeout" : "read-failed"
		};
	}
}
/**
* Notes about the tokens themselves, from `tokenRisk`: an issuer that can move or burn your balance,
* freeze it, or mint more (none for SOL, USDC and USDT, which keep them by design). When the mints
* could not be read, one note says so: unknown is never reported as nothing to note.
*/
async function tokenNotices(rpc, mints, timeoutMs = 1e4) {
	return noticesOf(await tokenRisk(rpc, mints, timeoutMs));
}
/** `tokenNotices` from a `tokenRisk` already read. */
function noticesOf(risk) {
	if (risk.status === "unavailable") return ["the tokens' mint accounts could not be read on your RPC: what their issuers can do is unknown"];
	const notes = [];
	for (const [m, t] of Object.entries(risk.tokens)) {
		if (!("wellKnown" in t) || t.wellKnown) continue;
		const name = `${m.slice(0, 4)}…${m.slice(-4)}`;
		if (t.permanentDelegate) notes.push(`${name} has a permanent delegate: its issuer can move or burn your balance at any time`);
		if (t.freezeAuthority) notes.push(`${name} has a freeze authority: its issuer can freeze your balance`);
		if (t.mintAuthority) notes.push(`${name} can still be minted by its issuer`);
	}
	return notes;
}
/**
* The transfer fee a Token-2022 input token charges in the current epoch, read on your RPC; null
* when it charges none (a classic token, or no TransferFeeConfig). For `ownMinimum`'s `inputTax`.
*/
async function inputTransferFee(rpc, mint, timeoutMs = 1e4) {
	const state = (await readAccounts(rpc, [mint], { timeoutMs })).accounts.get(mint);
	if (!state || state.owner !== TOKEN_2022_PROGRAM || !hasTransferFee(state.data)) return null;
	const { epoch } = await rpc.getEpochInfo({ commitment: "confirmed" }).send({ abortSignal: AbortSignal.timeout(timeoutMs) });
	return transferFeeOf(state.data, BigInt(epoch));
}
/**
* The most Orientim's fee in SOL may be for a swap that neither token can carry the fee for, from a
* price the agent asks Jupiter for itself: `maxFeeBps` (default 30) of what `amountIn` of the input
* is worth in SOL, plus 2% for the price moving between the server's quote and this one. In
* lamports.
*/
async function ownSolFeeLimit(args) {
	const url = new URL(args.jupiterUrl ?? "https://api.jup.ag/swap/v2/build");
	const query = {
		inputMint: args.inputMint,
		outputMint: "So11111111111111111111111111111111111111112",
		amount: args.amountIn,
		taker: args.taker,
		slippageBps: "50",
		maxAccounts: "64"
	};
	for (const [k, v] of Object.entries(query)) url.searchParams.set(k, v);
	const res = await (args.fetchImpl ?? fetch)(url.toString(), {
		headers: args.apiKey ? { "x-api-key": args.apiKey } : {},
		signal: AbortSignal.timeout(15e3)
	});
	if (!res.ok) throw new Error(`Jupiter answered ${res.status} when asked for the value of your swap in SOL`);
	const r = await res.json();
	if (r.inputMint !== args.inputMint || r.outputMint !== query.outputMint || r.inAmount !== args.amountIn || !/^\d{1,20}$/.test(r.outAmount ?? "")) throw new Error("Jupiter answered for another trade when asked for the value of your swap in SOL");
	const fee = BigInt(r.outAmount) * BigInt(feeLimitBps(args.maxFeeBps)) / 10000n;
	const limit = fee + fee / 50n;
	if (limit > BigInt(Number.MAX_SAFE_INTEGER)) throw new Error("the fee in SOL for this amount is beyond an exact limit; set maxSolFeeLamports yourself");
	return Number(limit);
}
//#endregion
export { DEFAULT_MAX_PRICE_IMPACT_BPS, MAX_BELOW_BPS, MAX_FEE_BPS, MAX_PRICE_IMPACT_BPS, MAX_SLIPPAGE_BPS, MIN_SLIPPAGE_BPS, ORIENTIM_TREASURY, STATUS_CACHE_BLOCKS, feeLimitBps, inputTransferFee, isSlippageBps, noticesOf, ownMinimum, ownQuote, ownSolFeeLimit, pastProof, provesNeverLanded, solFeeOf, tokenNotices, tokenRisk, verifyPrepared };
